### PR TITLE
Big Nail Carpenter Updates

### PR DESCRIPTION
**Pull request by wookywok**
(release 2)

- Made Nail Carpenter half-speed -- it shouldn't change much, just remember to double your tempo!

- Also changed the long nail input from hold and release to simply pressing B -- the old way gives less reaction time and is just less fun overall

- Also touched up the animations to make them snappier and improve gamefeel

### CODE REVIEW

**Comment by minenice55** [comment]
probably don't need the half-speed change since it's easy to just do so in the chart (plus the fancy patterns are awesome at full speed)

**Comment by minenice55** [comment]
assigning self to fox spawning issue

**Comment by fu-majime** [comment]
>Also changed the long nail input from hold and release to simply pressing B
Wouldn't it be better to use IAFlickCat for mouse controller of InputAction_AltPress?
The same could be said for the future implementation of Built to Scale (Wii).

**Comment by minenice55** [comment]
gonna undraft and merge the current progress, the rest can be finished once we have the new assets ready

**Pull request merged**
