### PR TITLE
Love Lab (R2) 

### PR DESCRIPTION
**Pull request by Mytiaoga**
Incomplete implementation of Love Lab

### CODE REVIEW

**Comment by minenice55** [comment]
5000+ changes?

**Comment by wookywok** [comment]
i checked the files, love lab isn't in this commit

**Comment by saladplainzone** [comment]
something weird with the "reup" commit, looks like you accidentally killed love lab?

**Comment by Mytiaoga** [comment]
sorry for that, now love lab is in the commit (for real)

**Pull request merged**
