### PR TITLE
NIGHT WALK ASSET BUNDLES

### PR DESCRIPTION
**Pull request by RaffyTaffy14**
YEAAAA NIGHT WALK ASSET BUNDLES

### CODE REVIEW

**Comment by fancythedeveloper** [comment]
does this mean i can finally update my SoU remix to use NW sfx instead of meat grinder lmao

**Comment by RaffyTaffy14** [comment]
you always could, fella

**Comment by fancythedeveloper** [comment]
does the Get SFX button work with more games than just the ones with assetbundles?

**Comment by RaffyTaffy14** [comment]
oops i missed the "sfx" part. get sfx button still works as before

**Comment by minenice55** [comment]
fix merge conflicts befire I can merge

**Comment by RaffyTaffy14** [comment]
dammit

**Pull request merged**
