### PR TITLE
Added Unused Spaceball Objects

### PR DESCRIPTION
**Pull request by wookywok**
- Apple drawn by me
- Star shamelessly stolen from Slot Monster

### CODE REVIEW

**Comment by fancythedeveloper** [comment]
i know the star's from tengoku, but then where did the apple come from?

**Comment by Placeholderjpeg** [comment]
tengoku too

**Comment by YourFriend87** [comment]
so i guess that what that random apple in finished-assets was doing there

**Comment by RaffyTaffy14** [comment]
so glad to see people finally figure out what the mystery apple was

**Comment by kkuhn317** [comment]
I KNEW IT
https://discord.com/channels/945450048832040980/945462438952828969/1204874223823233024

**Pull request merged**
