### PR TITLE
kill.

### PR DESCRIPTION
**Pull request by RaffyTaffy14**
kill the 30mb .wav

will probably reimplement more optimized at some point (it isn't even used anyway)

### CODE REVIEW

**Comment by RaffyTaffy14** [comment]
clap trap has big 4 minute ambience file

had to kill because it big and lag loading

**Comment by minenice55** [comment]
what the fuck

**Comment by GhostlyGuyGD** [comment]
how did nobody know this was in the files

**Comment by fancythedeveloper** [comment]
> how did nobody know this was in the files

you say that like all the bon odori shit wasn't there until recently

**Comment by RaffyTaffy14** [comment]
> how did nobody know this was in the files

i knew it was in the files

it just happened to be last night that i realized that having a .wav to load at that size is likely problematic

**Comment by saladplainzone** [comment]
ohhhhh, is that why it takes so long to load clap trap, lmao

**Comment by RaffyTaffy14** [comment]
> ohhhhh, is that why it takes so long to load clap trap, lmao

yea i connected the dots while marc was talking about manzai sounds or something

**Comment by RaffyTaffy14** [comment]
actually i never tested

**Comment by minenice55** [comment]
it seems to be better just has the typical "unpacked game" lag

**Pull request merged**
