### PR TITLE
Bug Fixes + Feature Additions

### PR DESCRIPTION
**Pull request by AstrlJelly**
* munchy monk input + mustache fixes
* fork lifter and pajama party bopping
* instant sleep block in pajama party, so you can start the game slept
 -you can set it to awake or no awake (they'll wake up a beat before the end of the block)
 -it also lets you technically set a custom wake up length to Slumber
* meat grinder miss bop fix
* cloud monkey in munchy monk
* marching orders Go! was broken
* force march doesn't break when it's too close to a game switch
* you can use the March! block without the marching

:)

### CODE REVIEW

**Comment by minenice55** [comment]
target branch to be changed to release_1, will grant "to-merge" tag

**Comment by minenice55** [comment]
need to go over minigame changes and see if update functions should be added

**Comment by MetalAshura** [comment]
lets get to merging

**Comment by Rapandrasmus** [comment]
😂

**Comment by minenice55** [comment]
> lets get to merging

there's a review that needs resolving

**Pull request merged**
