### PR TITLE
Tons of cleanup in TONS OF MINIGAMES!!!

### PR DESCRIPTION
**Pull request by Rapandrasmus**

### CODE REVIEW

**Comment by ThatZeoMan** [comment]
zeo

**Comment by ThatZeoMan** [comment]
(great work!!)

**Comment by GhostlyGuyGD** [comment]
ghostlyguy

**Comment by GhostlyGuyGD** [comment]
(great work!!)

**Comment by Saraistupid** [comment]
sara

**Comment by Saraistupid** [comment]
(great work!!)

**Pull request merged**
