### PR TITLE
Sumo brothers

### PR DESCRIPTION
**Pull request by RaffyTaffy14**
**WE ARE THE SUMO BROS!**

Slap your hands together and move like the bathing suits of a synchronized swimming team!
Stomp in synchronicity like a pair of three-year-old earthquakes having a tantrum!
Pose as impressively as a sunset made of platinum in perfect sync!

_May you perform and remix so well in the actual contest._

### CODE REVIEW

**Comment by RaffyTaffy14** [comment]
father minenice what do i do about this conflict

**Comment by minenice55** [comment]
> father minenice what do i do about this conflict

I'll deal with it

**Comment by blank3times** [comment]
> May you perform and remix so well in the actual contest.
Is there a remixing contest right now on the Discord?

**Comment by blank3times** [comment]
> > > _May you perform and remix so well in the actual contest._
> > 
> > 
> > Is there a remixing contest right now on the Discord?
> 
> no i'm just quoting the practice

Good to know. I'm taking time off Discord for some peace, so I wanna know this stuff to think about it ^-^

**Pull request merged**
