### PR TITLE
Monkey watch

### PR DESCRIPTION
**Pull request by Rapandrasmus**
I love monkeys watch
Basically done, only missing that shaky handy anim for missing when u zoomed out
Credit goes to astrl and ev for setting up the prefab stuff prior to me taking over and rewriting all the code

### CODE REVIEW

**Comment by Starpelly** [comment]
return to monke

**Comment by Rapandrasmus** [comment]
look guys the game was actually possible to make with some liberties taken on the camera movement 🤯🤯🤯

**Comment by Starpelly** [comment]
> look guys the game was actually possible to make with some liberties taken on the camera movement 🤯🤯🤯

i'm gonna need a source on that, liberal

**Comment by minenice55** [comment]
retarget to master we won't merge this to r1

**Comment by Rapandrasmus** [comment]
What the fuck happebed

**Comment by RaffyTaffy14** [comment]
glee club is now set to be the final r1 game as we set on releasing this sometime in april

**Comment by Rapandrasmus** [comment]
Fixed weird merge conflicts, ready to pull now

**Comment by blank3times** [comment]
Out of Rhythm Purgatory! It's kind of telling that it's already on page 3 of the closed PRs...

**Pull request merged**
