### PR TITLE
Hole in One

### PR DESCRIPTION
**Pull request by blank3times**
Ev let me do Hole in One, this branch should end up ahead of ev's.

### CODE REVIEW

**Comment by blank3times** [comment]
I don't see a way to deal with tags so it will have no tags for now. How would one add them?

**Comment by patataofcourse** [comment]
does this PR supersede #600 then?

**Comment by blank3times** [comment]
Yeah, ev is busy and not looking to work on the game right now.

**Comment by blank3times** [comment]
I've started my work directly on ev's branch, #600 will prevail.

**Pull request closed without merging**
