### PR TITLE
Night Walk GBA & Fever

### PR DESCRIPTION
**Pull request by Starpelly**
This will contain everything needed, both the games interact with each other seamlessly and there are a few extra features I don't want to spoil. This is a temp commit to make sure everything works and I need to finish a level before this will be finalized.

I wanted to say that I've had a lot of fun working with you guys, I treat this project as my child in a way, and I appreciate that you are able to still take care of it. I love everyone associated even if I don't act like it, or necessarily like everything someone does (looking at you, mods). I know some of you will probably hate me forever, that's OK, I'll remember this experience forever, so that's all that matters in the end.

### CODE REVIEW

**Comment by evdial** [comment]
goodbye king

**Comment by Rapandrasmus** [comment]
goodbye king

**Comment by AmericanMark** [comment]
Glad to see this community is starting to make a turn around.

**Comment by SheaButMyNameIsTaken** [comment]
> Glad to see this community is starting to make a turn around.

shut up you got banned 💀💀💀💀💀💀💀💀💀💀💀💀💀💀

**Comment by RaffyTaffy14** [comment]
> Glad to see this community is starting to make a turn around.

what are you on about mark

**Comment by SheaButMyNameIsTaken** [comment]
> Glad to see this community is starting to make a turn around.

Lil bro talking about some "turning around" 😭

**Comment by saladplainzone** [comment]
despite

**Comment by patataofcourse** [comment]
please refrain from causing drama in the github comments section.

**Comment by Starpelly** [comment]
I'm still willing to make builds for you guys, if you so ask.

**Comment by Starpelly** [comment]
Sorry this is taking a while, I shouldn't have made a promise. I'm really busy right now dealing with my job, I'm finishing it up. When it's done, it's done.

**Comment by Rapandrasmus** [comment]
We will be patient 🫡
Take as long as ya need brah

**Comment by saladplainzone** [comment]
Yeah no worries, take as long as you need

**Pull request closed without merging**
