### PR TITLE
Window Dancing

### PR DESCRIPTION
**Pull request by Firerise9402**
More stable and less broken than the last pr.

I think.

### CODE REVIEW

**Comment by minenice55** [comment]
need someone to test on platforms other than Windows

**Comment by Firerise9402** [comment]
Also need someone to code the window dance for mac. I don't know if anyone wants to go through getting it on linux.

**Comment by Firerise9402** [comment]
Ok so I don't know why or how, but for some reason whenever I use save as and save over an existing riq file it crashes heavenstudio. But it doesn't in unity. Please tell me if you have a fix because idk why it does that.

**Comment by ThatZeoMan** [comment]
Are you on mac? Make sure Discord Rich Presence is turned off in the Editor Settings, otherwuse it could cause problems

**Comment by Firerise9402** [comment]
Nope, Windows. My theory is that the new blocks frick up the saving process, but that doesn't explain why just doing ctrl s works fine, or making a new file.

**Comment by ThatZeoMan** [comment]
Could you send the log file of the crash?

**Comment by Firerise9402** [comment]
`Crash!!!
SymInit: Symbol-SearchPath: '.;C:\Users\firer\Downloads\another temp bluild thingy i can spell;C:\Users\firer\Downloads\another temp bluild thingy i can spell;C:\Windows;C:\Windows\system32;', symOptions: 534, UserName: 'firer'
OS-Version: 10.0.0
C:\Users\firer\Downloads\another temp bluild thingy i can spell\Heaven Studio.exe:Heaven Studio.exe (00AB0000), size: 655360 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 2021.3.21.5473
C:\Windows\SYSTEM32\ntdll.dll:ntdll.dll (774F0000), size: 1720320 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.3155
C:\Windows\System32\KERNEL32.DLL:KERNEL32.DLL (76F30000), size: 983040 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.3155
C:\Windows\System32\KERNELBASE.dll:KERNELBASE.dll (772A0000), size: 2334720 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.3208
C:\Users\firer\Downloads\another temp bluild thingy i can spell\UnityPlayer.dll:UnityPlayer.dll (78B60000), size: 23810048 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 2021.3.21.5473
C:\Windows\System32\USER32.dll:USER32.dll (75EC0000), size: 1687552 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.3155
C:\Windows\System32\win32u.dll:win32u.dll (77230000), size: 98304 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.3208
C:\Windows\System32\GDI32.dll:GDI32.dll (76EE0000), size: 147456 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.2913
C:\Windows\System32\gdi32full.dll:gdi32full.dll (76C60000), size: 937984 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.2965
C:\Windows\System32\msvcp_win.dll:msvcp_win.dll (757D0000), size: 503808 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.789
C:\Windows\System32\ucrtbase.dll:ucrtbase.dll (76620000), size: 1179648 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.789
C:\Windows\System32\ole32.dll:ole32.dll (75410000), size: 929792 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.2965
C:\Windows\System32\RPCRT4.dll:RPCRT4.dll (75850000), size: 782336 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.3208
C:\Windows\SYSTEM32\VERSION.dll:VERSION.dll (74B60000), size: 32768 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\System32\combase.dll:combase.dll (75A00000), size: 2621440 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.2788
C:\Windows\System32\msvcrt.dll:msvcrt.dll (75710000), size: 782336 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 7.0.19041.546
C:\Windows\System32\SHLWAPI.dll:SHLWAPI.dll (77250000), size: 282624 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.2075
C:\Windows\System32\SETUPAPI.dll:SETUPAPI.dll (76740000), size: 4423680 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.3155
C:\Windows\System32\cfgmgr32.dll:cfgmgr32.dll (75910000), size: 241664 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.3155
C:\Windows\System32\bcrypt.dll:bcrypt.dll (76F10000), size: 102400 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.3208
C:\Windows\System32\ADVAPI32.dll:ADVAPI32.dll (76B80000), size: 507904 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.2913
C:\Windows\System32\sechost.dll:sechost.dll (75500000), size: 483328 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.2913
C:\Windows\System32\SHELL32.dll:SHELL32.dll (76060000), size: 5988352 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.3208
C:\Windows\System32\OLEAUT32.dll:OLEAUT32.dll (75960000), size: 614400 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.3208
C:\Windows\System32\IMM32.dll:IMM32.dll (770E0000), size: 151552 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.2673
C:\Windows\SYSTEM32\OPENGL32.dll:OPENGL32.dll (5CB90000), size: 1060864 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.2193
C:\Windows\System32\CRYPT32.dll:CRYPT32.dll (75C80000), size: 1048576 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.3208
C:\Windows\SYSTEM32\WINMM.dll:WINMM.dll (75220000), size: 163840 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\System32\WS2_32.dll:WS2_32.dll (771C0000), size: 405504 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\SYSTEM32\WINHTTP.dll:WINHTTP.dll (74B90000), size: 827392 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.3031
C:\Windows\SYSTEM32\HID.DLL:HID.DLL (74180000), size: 40960 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\SYSTEM32\GLU32.dll:GLU32.dll (5CB50000), size: 258048 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.2193
C:\Windows\SYSTEM32\dwmapi.dll:dwmapi.dll (640A0000), size: 155648 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.746
C:\Windows\SYSTEM32\kernel.appcore.dll:kernel.appcore.dll (74B70000), size: 61440 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\System32\bcryptPrimitives.dll:bcryptPrimitives.dll (76C00000), size: 389120 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.2486
C:\Windows\system32\uxtheme.dll:uxtheme.dll (710B0000), size: 475136 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.2193
C:\Windows\System32\shcore.dll:shcore.dll (75D80000), size: 552960 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1645
C:\Windows\SYSTEM32\windows.storage.dll:windows.storage.dll (71A90000), size: 6344704 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.3208
C:\Windows\SYSTEM32\Wldp.dll:Wldp.dll (71240000), size: 151552 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.3208
C:\Windows\SYSTEM32\profapi.dll:profapi.dll (70840000), size: 114688 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.3155
C:\Users\firer\Downloads\another temp bluild thingy i can spell\MonoBleedingEdge\EmbedRuntime\mono-2.0-bdwgc.dll:mono-2.0-bdwgc.dll (5C0C0000), size: 6467584 (result: 0), SymType: '-deferred-', PDB: ''
C:\Windows\SYSTEM32\iphlpapi.dll:iphlpapi.dll (70360000), size: 208896 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.2788
C:\Windows\System32\MSCTF.dll:MSCTF.dll (75630000), size: 868352 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.2673
C:\Windows\SYSTEM32\d3d11.dll:d3d11.dll (63E10000), size: 1966080 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.2913
C:\Windows\SYSTEM32\dxgi.dll:dxgi.dll (67260000), size: 794624 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.2311
C:\Windows\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_19f3764f95906f94\nvldumd.dll:nvldumd.dll (63C00000), size: 614400 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 31.0.15.3179
C:\Windows\SYSTEM32\msasn1.dll:msasn1.dll (74190000), size: 57344 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.2251
C:\Windows\SYSTEM32\cryptnet.dll:cryptnet.dll (6EE20000), size: 155648 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.906
C:\Windows\SYSTEM32\drvstore.dll:drvstore.dll (67E70000), size: 1048576 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.2546
C:\Windows\SYSTEM32\devobj.dll:devobj.dll (741E0000), size: 167936 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.3155
C:\Windows\SYSTEM32\cryptbase.dll:cryptbase.dll (720A0000), size: 40960 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\System32\WINTRUST.DLL:WINTRUST.DLL (75E10000), size: 311296 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.2913
C:\Windows\System32\imagehlp.dll:imagehlp.dll (77110000), size: 102400 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1415
C:\Windows\SYSTEM32\CRYPTSP.dll:CRYPTSP.dll (72B40000), size: 77824 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\system32\rsaenh.dll:rsaenh.dll (720B0000), size: 192512 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1052
C:\Windows\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_19f3764f95906f94\nvwgf2um.dll:nvwgf2um.dll (0EAC0000), size: 59326464 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 31.0.15.3179
C:\Windows\system32\nvspcap.dll:nvspcap.dll (613B0000), size: 2269184 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 3.27.0.112
C:\Windows\SYSTEM32\ntmarta.dll:ntmarta.dll (74210000), size: 167936 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\SYSTEM32\dxcore.dll:dxcore.dll (689D0000), size: 180224 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\System32\clbcatq.dll:clbcatq.dll (75390000), size: 516096 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 2001.12.10941.16384
C:\Windows\system32\wbem\wbemprox.dll:wbemprox.dll (70050000), size: 53248 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1320
C:\Windows\SYSTEM32\wbemcomn.dll:wbemcomn.dll (70160000), size: 458752 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1566
C:\Windows\system32\wbem\wbemsvc.dll:wbemsvc.dll (70040000), size: 65536 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1320
C:\Windows\system32\wbem\fastprox.dll:fastprox.dll (6FEF0000), size: 823296 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\SYSTEM32\amsi.dll:amsi.dll (6FE40000), size: 98304 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.2075
C:\Windows\SYSTEM32\USERENV.dll:USERENV.dll (74CF0000), size: 151552 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.3155
C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.23050.9-0\X86\MpOav.dll:MpOav.dll (6FDD0000), size: 438272 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 4.18.23050.9
C:\Windows\System32\MMDevApi.dll:MMDevApi.dll (671B0000), size: 438272 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.2075
C:\Windows\SYSTEM32\AUDIOSES.DLL:AUDIOSES.DLL (5B170000), size: 1269760 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1741
C:\Windows\SYSTEM32\powrprof.dll:powrprof.dll (6EDD0000), size: 278528 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\SYSTEM32\UMPDC.dll:UMPDC.dll (6EDC0000), size: 53248 (result: 0), SymType: '-deferred-', PDB: ''
C:\Windows\SYSTEM32\resourcepolicyclient.dll:resourcepolicyclient.dll (68480000), size: 61440 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\SYSTEM32\xinput1_3.dll:xinput1_3.dll (00400000), size: 90112 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 9.18.944.0
C:\Windows\SYSTEM32\dcomp.dll:dcomp.dll (63CA0000), size: 1458176 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.2913
C:\Windows\SYSTEM32\textinputframework.dll:textinputframework.dll (68380000), size: 757760 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.3031
C:\Windows\SYSTEM32\CoreMessaging.dll:CoreMessaging.dll (682E0000), size: 634880 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.3208
C:\Windows\SYSTEM32\CoreUIComponents.dll:CoreUIComponents.dll (68060000), size: 2613248 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\SYSTEM32\wintypes.dll:wintypes.dll (70060000), size: 897024 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.2788
C:\Windows\system32\Oleacc.dll:Oleacc.dll (63990000), size: 339968 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 7.2.19041.746
C:\Users\firer\Downloads\another temp bluild thingy i can spell\Heaven Studio_Data\Plugins\x86\JoyShockLibrary.dll:JoyShockLibrary.dll (64110000), size: 73728 (result: 0), SymType: '-deferred-', PDB: ''
C:\Windows\SYSTEM32\MSVCP140.dll:MSVCP140.dll (752C0000), size: 446464 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 14.36.32532.0
C:\Windows\SYSTEM32\VCRUNTIME140.dll:VCRUNTIME140.dll (752A0000), size: 86016 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 14.36.32532.0
C:\Windows\System32\comdlg32.dll:comdlg32.dll (75580000), size: 716800 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1806
C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.1110_none_a8625c1886757984\COMCTL32.dll:COMCTL32.dll (67690000), size: 2162688 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 6.10.19041.1110
C:\Windows\System32\DUI70.dll:DUI70.dll (60570000), size: 1437696 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.746
C:\Windows\System32\DUser.dll:DUser.dll (64510000), size: 487424 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Program Files (x86)\Common Files\microsoft shared\ink\tiptsf.dll:tiptsf.dll (643A0000), size: 536576 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.746
C:\Windows\SYSTEM32\atlthunk.dll:atlthunk.dll (6F5B0000), size: 53248 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\SYSTEM32\TextShaping.dll:TextShaping.dll (5F610000), size: 606208 (result: 0), SymType: '-deferred-', PDB: ''
C:\Windows\SYSTEM32\edputil.dll:edputil.dll (70820000), size: 110592 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\system32\explorerframe.dll:explorerframe.dll (55D40000), size: 1732608 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1949
C:\Windows\SYSTEM32\WindowsCodecs.dll:WindowsCodecs.dll (57920000), size: 1511424 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1706
C:\Windows\System32\thumbcache.dll:thumbcache.dll (53AC0000), size: 294912 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1466
C:\Windows\SYSTEM32\policymanager.dll:policymanager.dll (58110000), size: 536576 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.3155
C:\Windows\SYSTEM32\msvcp110_win.dll:msvcp110_win.dll (6F9E0000), size: 413696 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\system32\dataexchange.dll:dataexchange.dll (63FF0000), size: 200704 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1387
C:\Windows\system32\twinapi.appcore.dll:twinapi.appcore.dll (6EFD0000), size: 1654784 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.3031
C:\Windows\System32\Windows.UI.FileExplorer.dll:Windows.UI.FileExplorer.dll (644D0000), size: 245760 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1566
C:\Windows\System32\PROPSYS.dll:PROPSYS.dll (70860000), size: 794624 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 7.0.19041.1741
C:\Windows\System32\uiautomationcore.dll:uiautomationcore.dll (65900000), size: 2568192 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 7.2.19041.2788
C:\Windows\SYSTEM32\sxs.dll:sxs.dll (57B70000), size: 552960 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.2788
C:\Windows\System32\StructuredQuery.dll:StructuredQuery.dll (64750000), size: 528384 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 7.0.19041.746
C:\Windows\System32\Windows.FileExplorer.Common.dll:Windows.FileExplorer.Common.dll (61360000), size: 299008 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1566
C:\Windows\System32\iertutil.dll:iertutil.dll (70410000), size: 2281472 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 11.0.19041.3208
C:\Windows\System32\Windows.StateRepositoryPS.dll:Windows.StateRepositoryPS.dll (612C0000), size: 602112 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.3155
C:\Windows\system32\Windows.Storage.Search.dll:Windows.Storage.Search.dll (604D0000), size: 643072 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.3155
C:\Windows\system32\IconCodecService.dll:IconCodecService.dll (68850000), size: 32768 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1
C:\Windows\System32\coml2.dll:coml2.dll (75E60000), size: 385024 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\SYSTEM32\MPR.dll:MPR.dll (6FDB0000), size: 102400 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1806
C:\Windows\System32\drprov.dll:drprov.dll (644A0000), size: 36864 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\System32\WINSTA.dll:WINSTA.dll (6B710000), size: 290816 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.3155
C:\Windows\System32\ntlanman.dll:ntlanman.dll (640E0000), size: 98304 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.2604
C:\Windows\System32\davclnt.dll:davclnt.dll (63A80000), size: 102400 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\System32\DAVHLPR.dll:DAVHLPR.dll (64490000), size: 40960 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\System32\wkscli.dll:wkscli.dll (6E1A0000), size: 77824 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.3155
C:\Windows\SYSTEM32\LINKINFO.dll:LINKINFO.dll (57AB0000), size: 45056 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\SYSTEM32\cscapi.dll:cscapi.dll (6DD00000), size: 57344 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\System32\netutils.dll:netutils.dll (70640000), size: 45056 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1466
C:\Windows\System32\ActXPrxy.dll:ActXPrxy.dll (60480000), size: 303104 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.2546
C:\Windows\System32\twinapi.dll:twinapi.dll (639F0000), size: 532480 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.3155
C:\Windows\SYSTEM32\apphelp.dll:apphelp.dll (6E850000), size: 655360 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.2913
C:\Windows\System32\dlnashext.dll:dlnashext.dll (60430000), size: 274432 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.3155
C:\Windows\System32\PlayToDevice.dll:PlayToDevice.dll (603E0000), size: 299008 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.746
C:\Windows\System32\DevDispItemProvider.dll:DevDispItemProvider.dll (6DEB0000), size: 110592 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\system32\wpdshext.dll:wpdshext.dll (60350000), size: 569344 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1949
C:\Windows\WinSxS\x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.19041.2251_none_d9513b1fe1046fc7\gdiplus.dll:gdiplus.dll (68A00000), size: 1470464 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.2251
C:\Windows\System32\PortableDeviceApi.dll:PortableDeviceApi.dll (602C0000), size: 536576 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.746
C:\Windows\System32\PortableDeviceTypes.dll:PortableDeviceTypes.dll (61290000), size: 159744 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.746
C:\Users\firer\AppData\Local\Microsoft\OneDrive\23.147.0716.0001\i386\FileSyncShell.dll:FileSyncShell.dll (600F0000), size: 1605632 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 23.147.716.1
C:\Windows\SYSTEM32\Secur32.dll:Secur32.dll (741D0000), size: 40960 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\SYSTEM32\WININET.dll:WININET.dll (6BC40000), size: 4542464 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 11.0.19041.3031
C:\Windows\SYSTEM32\WTSAPI32.dll:WTSAPI32.dll (75250000), size: 61440 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\SYSTEM32\SSPICLI.DLL:SSPICLI.DLL (741A0000), size: 135168 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.2130
C:\Windows\SYSTEM32\ntshrui.dll:ntshrui.dll (55370000), size: 376832 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.844
C:\Windows\SYSTEM32\srvcli.dll:srvcli.dll (70650000), size: 122880 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.3155
C:\Windows\System32\cldapi.dll:cldapi.dll (5F6E0000), size: 114688 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1682
C:\Windows\System32\FLTLIB.DLL:FLTLIB.DLL (70140000), size: 32768 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\system32\NetworkExplorer.dll:NetworkExplorer.dll (5F830000), size: 77824 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1
C:\Windows\SYSTEM32\PhotoMetadataHandler.dll:PhotoMetadataHandler.dll (5C050000), size: 430080 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.746
C:\Windows\System32\provsvc.dll:provsvc.dll (5F7C0000), size: 401408 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1466
C:\Users\firer\Downloads\another temp bluild thingy i can spell\MonoBleedingEdge\EmbedRuntime\MonoPosixHelper.dll:MonoPosixHelper.dll (5BFD0000), size: 479232 (result: 0), SymType: '-deferred-', PDB: ''
C:\Windows\System32\MrmCoreR.dll:MrmCoreR.dll (536C0000), size: 778240 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1566
C:\Windows\SYSTEM32\windows.staterepositorycore.dll:windows.staterepositorycore.dll (64390000), size: 49152 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.3155
C:\Windows\System32\bcp47mrm.dll:bcp47mrm.dll (6FCA0000), size: 139264 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1503
C:\Windows\System32\Windows.UI.dll:Windows.UI.dll (65800000), size: 995328 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.746
C:\Windows\System32\WindowManagementAPI.dll:WindowManagementAPI.dll (65780000), size: 471040 (result: 0), SymType: '-deferred-', PDB: ''
C:\Windows\System32\InputHost.dll:InputHost.dll (665F0000), size: 970752 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1741
C:\Windows\System32\mfsrcsnk.dll:mfsrcsnk.dll (5BE70000), size: 1425408 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.906
C:\Windows\System32\RTWorkQ.DLL:RTWorkQ.DLL (654A0000), size: 167936 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1741
C:\Windows\System32\MFPlat.DLL:MFPlat.DLL (654D0000), size: 1544192 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1865
C:\Windows\System32\OneCoreUAPCommonProxyStub.dll:OneCoreUAPCommonProxyStub.dll (68490000), size: 3903488 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.3031
C:\Windows\system32\xmllite.dll:xmllite.dll (60290000), size: 176128 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\system32\audiodev.dll:audiodev.dll (5F700000), size: 262144 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1
C:\Windows\system32\WMVCore.DLL:WMVCore.DLL (54690000), size: 2150400 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 12.0.19041.3031
C:\Windows\system32\WMASF.DLL:WMASF.DLL (58610000), size: 249856 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 12.0.19041.1
C:\Windows\system32\mfperfhelper.dll:mfperfhelper.dll (65150000), size: 1073152 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1
C:\Windows\System32\urlmon.dll:urlmon.dll (70670000), size: 1740800 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 11.0.19041.3155
C:\Windows\SYSTEM32\dbghelp.dll:dbghelp.dll (6DB70000), size: 1605632 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1052

========== OUTPUTTING STACK TRACE ==================

A crash has been intercepted by the crash handler. For call stack and other details, see the latest crash report generated in:
 * C:/Users/firer/AppData/Local/Temp/RHeavenStudio/Heaven Studio/Crashes`
Thats the crash. Nothing related to it happens before in the log.

**Comment by ThatZeoMan** [comment]
it would still be helpful to see the player.log :cherryhappy:

**Comment by Firerise9402** [comment]
[Player.log](https://github.com/RHeavenStudio/HeavenStudio/files/12296959/Player.log)
Here you go, little long because that session I was editing a beatmap before crashing it kinda on purpose.

**Comment by ThatZeoMan** [comment]
Does it still crash even if theres no window dance events?

**Comment by Firerise9402** [comment]
Yep, just checked. only thing in the map was an end remix block.

**Comment by Firerise9402** [comment]
Interesting thing is it works in the unity editor but not when built. Might have something to do with it trying to resize things that shouldn't be resized with the saving dialogue, but I don't know.

**Comment by Firerise9402** [comment]
Closing so that I can fix the branch being pr-ed and all that this is a mess.

**Pull request closed without merging**
