### PR TITLE
Viewport Scale fix

### PR DESCRIPTION
**Pull request by Firerise9402**
Changes the units viewport scale uses to make it clearer and easier to use when scaling both up and down.
Does not currently have parity changes.

### CODE REVIEW

**Comment by ThatZeoMan** [comment]
Does this have compatibility with old events? As in, does an old viewport scale event still scale the same amount when converted to the new units?

**Comment by Firerise9402** [comment]
Let me check real quick.

**Comment by Firerise9402** [comment]
Ok it doesn't let me add some fixes so it does.

**Comment by Firerise9402** [comment]
Ok I'm not entirely sure how to set up parity for this kind of thing, I think I'll just leave this on the table for now and maybe figure it out later.

**Comment by ThatZeoMan** [comment]
Theres an riqentity updater that can automatically run a predefined convert function if it detects an entity version mismatch, ask @AstrlJelly about how to use it
(I only learned of this 5 minutes ago)

**Pull request closed without merging**
