### PR TITLE
Editor Rewrite

### PR DESCRIPTION
**Pull request by Starpelly**
This is a pull draft right now, but here is everything planned so far.

- [ ] Full undo/redo support
- [ ] Full window docking
- [ ] Full support for multiple entity parameter types including:
    - [x] Pitch
    - [ ] Vector2
    - [ ] Vector3
    - [ ] List<T>
    - [ ] Number (int, float, double)
    - [ ] Checkmark (bool)
    - [ ] Dropdown (array)
    - [ ] InputField (string)
- [ ] Custom themes
- [ ] Copy & Paste
- [ ] Zoomable & Stretchable Timeline
- [ ] 8 Layers
- [ ] Pattern saving
- [x] Timeline waveform
- [ ] Custom textures
- [ ] Auto song offset
- [ ] Very simple scene editor for positioning cameras, captions, objects, etc.

### CODE REVIEW

**Comment by Saraistupid** [comment]
can you make a checklist of what you have worked on?

**Comment by GhostlyGuyGD** [comment]
This will be exciting

**Comment by Starpelly** [comment]
ugh

**Comment by Starpelly** [comment]
In one month someone DM me to join again so i can work on this.
There's a channel that sends github updates in the Discord I know someone can see this

**Pull request closed without merging**
