### PR TITLE
Octopus Machine Finalized

### PR DESCRIPTION
**Pull request by AstrlJelly**
this game is like karate man levels of modifiability lol

other than the basic gameplay of octopus machine this includes:
* custom hit and miss text which also triggers different bop animations
* text that can be changed at any time (includes the "You" at the bottom of the screen)
* you're able to move, change the color of, and make invisible the octopodes
* bubbles (idea courtesy of seanski), which are particle effects, one layer in front of the octopodes, the other behind, which you can change the speed and amount of
* force squeeze (akin to the dazzles force hold)

and i think that's it ‼️

### CODE REVIEW

**Comment by blank3times** [comment]
Karate Man levels sounds awesome! :o

**Comment by RaffyTaffy14** [comment]
no way munchy monk sounds awesome too!!! :o

**Comment by blank3times** [comment]
> 

"this game is like karate man levels of modifiability lol"

Perhaps my comment wasn't particularly clear, but this is what I was trying to be excited about.

Indeed Munchy Monk is pleasant to the ears as well, although I missed the relevancy outside of satire as you missed the relevancy of mine. =]

'I suppose' Discord is a better place to be excited than Github anyways, I'll attempt to keep that in mind so y'all have less clutter here.

**Comment by wookywok** [comment]
> 

I hope so, there's a whole channel on the discord that updates whenever there's anything happens on the github

**Pull request merged**
