### PR TITLE
Window Dancing

### PR DESCRIPTION
**Pull request by Firerise9402**
Mac still doesn't work, and I'm waiting for people who know how to do it to get back to me, for now, it can work and be commit. There's leftover commented out code from working on the mac version of this, but I'll clean that up shortly. Also, the save overwrite crash is fixed! I have no clue what caused it.

To Do:

- [x] Windows Support
- [x] Mac Support
- [x] Linux Support (unlikely) - canceled
- [x] Settings Toggle Option
- [ ] Cleaning up

### CODE REVIEW

**Comment by Firerise9402** [comment]
This is final for this pr, I'll do the mac version in another pr.

**Comment by minenice55** [comment]
holding until the feature can be made for other platforms

**Comment by Firerise9402** [comment]
Ok that's a lot of conflicts but hey it works now for mac! Linux won't work so I think this is done.

**Comment by Firerise9402** [comment]
At least I think it works for mac. Someone build this and test it please it should work.

**Comment by Firerise9402** [comment]
Unbroke it

**Comment by Firerise9402** [comment]
so um big update: im probably gonna be closing this for the time being because i didn't know how to manage branches and forks on github when i made this. i wont close it until i get a new fork up and running but don't accept this one.

**Pull request closed without merging**
