### PR TITLE
Mr. Upbeat Rework

### PR DESCRIPTION
**Pull request by AstrlJelly**
* made the game work like space soccer, where a "start stepping" block makes the blipping happen, and mr. upbeat starts stepping at the end of the block
* KILLED mr. downbeat (forces inputs to always be on the offbeat)
* changed default background color + added color changing for the bg and the blip color
* added the blip growing thing + text
* changed the spritesheet for the upscaled version (courtesy of seanski!!!)

i think that's everything. sorry for ruining your remixes with mr. upbeat again....

### CODE REVIEW

**Comment by Saraistupid** [comment]
> KILLED mr. downbeat (forces inputs to always be on the offbeat)

me when i'm not fun at parties

**Comment by AstrlJelly** [comment]
i killed him and i have no remorse for it

**Comment by Saraistupid** [comment]
i'll fucking kill you

**Comment by AstrlJelly** [comment]
revived mr. downbeat.... ready to merge.
if an animator wants to animate the missing miss anim then u can but for now i really do not want to

**Pull request merged**
