### PR TITLE
Slot Monster

### PR DESCRIPTION
**Pull request by AstrlJelly**
a nearly finished slot monster!!
needs a few things, like the coin pile and some planned curtain stuff. but most stuff is already in :)

### CODE REVIEW

**Comment by blank3times** [comment]
Oh it's real

Is it like C&R?

**Comment by AstrlJelly** [comment]
yep! limited to 3 inputs lol

**Comment by blank3times** [comment]
Perfect, I'm glad it worked out -u-

**Comment by blank3times** [comment]
Aurgh, I wish I was with my computer T-T

Excited to try and find good applications for this soon!

**Pull request merged**
