### PR TITLE
Auto KM Bulb, Dupe Block Removed

### PR DESCRIPTION
**Pull request by AstrlJelly**
oh ALSO PLAY ANIM BUG FIX. YAY.
all i had to do was change ["value"] to .value and ["Values"] to .Value
i just love programming sometimes 😃 😃 😃 😃 

* fixed duplicate keys being put into dynamic data, oops (there were ifs instead of else ifs)

this is for r1.1

### CODE REVIEW

**Comment by minenice55** [comment]
is it ok if I cherry-picked some of these changes into one of my current working branches because I am also touching karate man plus I finally properly implemented HS' side of entity versioning there

**Comment by AstrlJelly** [comment]
yeah, sure

**Comment by minenice55** [comment]
temp drafting since commits will be present in future pr

**Comment by minenice55** [comment]
integrated into #929, closing

**Pull request closed without merging**
