### PR TITLE
Screen Tiling

### PR DESCRIPTION
**Pull request by Firerise9402**
Adds Screen Tiling (similar to ADOFAI's screen tile effect) and the ability to scale the letterbox (SCRAPPED) so that you can make the game view take up the full window.

Fixed everything and is now ready I think.

### CODE REVIEW

**Comment by Firerise9402** [comment]
Hang on somethings broken

**Comment by Firerise9402** [comment]
Fixed

**Comment by Firerise9402** [comment]
it broke again

**Comment by minenice55** [comment]
think you could put both features in separate PRs? would be easier to merge and check out

**Comment by Firerise9402** [comment]
ok so I fixed it mostly but I'm working out some bugs with the overlay not tiling correctly

**Comment by Firerise9402** [comment]
oh frick something broke i think

**Comment by Firerise9402** [comment]
Nvm ignore that i just did something stupid when merging to my master branch the pr's branch is fine

**Comment by Firerise9402** [comment]
Closed because ras did it instead.

**Pull request closed without merging**
