### PR TITLE
Trick on the Class Overhaul

### PR DESCRIPTION
**Pull request by minenice55**
# Minigames
### Trick on the Class
image
- adds the missing object types
# Editor
- Chronological sorting now properly categorizes Mobile and PC / Other

### CODE REVIEW

**Comment by blank3times** [comment]
Optic blast?

**Comment by vinceiis** [comment]
optic blast

**Comment by minenice55** [comment]
optic blast

**Comment by RaffyTaffy14** [comment]
wildbreath flies
optic blast

**Pull request merged**
