### PR TITLE
Update Credits.txt

### PR DESCRIPTION
**Pull request by ThePurpleAnon**
hi my name is in now hi hi

### CODE REVIEW

**Comment by minenice55** [comment]
will target this for r2 since that's where manzai is going (let me know if I'm wrong)

**Comment by ThePurpleAnon** [comment]
i think it should be on master now since manzai is here too

**Comment by minenice55** [comment]
master is r2

**Comment by ThePurpleAnon** [comment]
yeah exactly
so yes ig
but also if manzai is currently in this version of the game why shouldn't my name be too

**Comment by minenice55** [comment]
when this targets r2 it means that it won't get cherry-picked to the r1 patches branch by the bot

**Pull request merged**
