### PR TITLE
New Editor

### PR DESCRIPTION
**Pull request by Starpelly**
The first pull to the new official editor.

New Editor is dubbed "RIQEditor".

Features planned (for right now):

- [ ] Full Undo-Redo system
- [ ] All of the features of the old editor
- [ ] Nodes & post processing
- [ ] Shortcut customization
- [ ] Theme editor
- [ ] Toggleable Autosave
- [ ] Save and load notifications
- [x] Clean UI

### CODE REVIEW

**Comment by Starpelly** [comment]
image

**Comment by RaffyTaffy14** [comment]
image

**Comment by Starpelly** [comment]
> image

Geometry dash mfs when they see a hammer and wrench

**Comment by RaffyTaffy14** [comment]
image

**Comment by blank3times** [comment]
Just make it TotallyRIQLogo

**Comment by Starpelly** [comment]
Little break, be back in a few days
image

**Comment by Starpelly** [comment]
All right all my stuff is done, I say we're back

**Pull request closed without merging**
