### PR TITLE
Fillbots (RELEASE 2)

### PR DESCRIPTION
**Pull request by Rapandrasmus**
This game is not for release 1.
A lot of stuff will be recolorable.
Ability to make custom bots with custom hold lengths.

### CODE REVIEW

**Comment by AstrlJelly** [comment]
this pr should probably be closed

**Comment by AstrlJelly** [comment]
yes unfortunately we are NOT adding fillbots to heaven studio! we hate it so much. stop trying ://

**Comment by Rapandrasmus** [comment]
I will literally smoke dog treats in the light of this information

**Comment by blank3times** [comment]
wait noooooooooooooooooooooooo :(((((((

tragic

**Comment by Untitled9528** [comment]
so true

**Comment by ookiooclapclap** [comment]
also, we should probably update the "minigames" project page

it says it was last updated in february, and since then, a lot of new Nightly games have popped up

**Comment by RaffyTaffy14** [comment]
> Fillbots 2 (DS) does suck tho ngl

MAJOR skill issue

**Comment by MiiKEmblem** [comment]
Fillbots

**Pull request closed without merging**
