### PR TITLE
Lockstep Inactive Cuing + Nightwalk GBA Fixes

### PR DESCRIPTION
**Pull request by AstrlJelly**
the way lockstep uses inactive cues is kinda weird but this works
nightwalk gba finally fixed !?!??! it's at least fixed in one chart so dm me bugs if you find them

### CODE REVIEW

**Comment by AstrlJelly** [comment]
i would hope? once it's merged feel free to send me charts that still aren't working. i don't want nw gba bugs anymore ❌

**Comment by beam-cat** [comment]
once im able i'll search all my nightwalk charts for potential fuckery

**Comment by AstrlJelly** [comment]
already found a bug, lemme see if i can squash that rq

**Comment by AstrlJelly** [comment]
all good now

**Comment by minenice55** [comment]
split the PR into two so that the lockstep stuff can go into R1

**Pull request closed without merging**
