### PR TITLE
Love Lab (R2)

### PR DESCRIPTION
**Pull request by iloveoatmeal2022**
all visuals done

### CODE REVIEW

**Comment by blank3times** [comment]
Is this the project Generic promised the assets were for? Was ReMegamixed that? I'm not on Discord so I'm kinda out of the loop.

**Comment by minenice55** [comment]
> Is this the project Generic promised the assets were for? Was ReMegamixed that? I'm not on Discord so I'm kinda out of the loop.

what's remegamixed

**Comment by RaffyTaffy14** [comment]
> Is this the project Generic promised the assets were for? Was ReMegamixed that? I'm not on Discord so I'm kinda out of the loop.

no

**Comment by blank3times** [comment]
> what's remegamixed

My misspelling of R. H. Re-Megamix (a m()dpack)🤦 🤦 🤦

**Pull request closed without merging**
