### PR TITLE
a few little fixes

### PR DESCRIPTION
**Pull request by AstrlJelly**
* mr upbeat input bug fixed
* munchy monk blush bug fixed
* mannequin factory icon + make icon import settings more consistent

### CODE REVIEW

**Comment by minenice55** [comment]
may I suggest splitting this PR in two, one PR with the fixes to the R1 games and another with the updated munchy monk icon
this way the commits can go to the right places

**Comment by AstrlJelly** [comment]
oh the input stuff will be in r1.1?

**Comment by minenice55** [comment]
yes

**Comment by minenice55** [comment]
(I'll close this so that you can do that)

**Pull request closed without merging**
