### PR TITLE
Cleaning up those dang warnings

### PR DESCRIPTION
**Pull request by ThePurpleAnon**
please clean up your compiler warnings before you make a PR from now on, or i will find you

if anybody wants to know what i changed, just search the codebase for "- marc" and you should be able to find all the code i commented out

### CODE REVIEW

**Comment by blank3times** [comment]
legend

**Comment by minenice55** [comment]
this touches source files added by external plugins? may be a good idea not to touch those since they come from outside the project (basically everything that was touched in the X-PostProcessing source files)

**Comment by ThePurpleAnon** [comment]
> this touches source files added by external plugins? may be a good idea not to touch those since they come from outside the project (basically everything that was touched in the X-PostProcessing source files)

every bit of documentation i found online told me that replacing the deprecated functions with the new ones was recommended. plus, each deprecated function was identical, and the new functions are identical as well. i can double check that things still work if you need but all signs point to this being fine.

**Comment by ThePurpleAnon** [comment]
tested, placing down new filter blocks does work, i'll make sure loading old filter blocks works too

**Comment by ThePurpleAnon** [comment]
yup, everything's dandy! you should be good to merge

**Comment by minenice55** [comment]
generally files imported from plugins shouldn't be touched since it's likely that changes get lost when updating them etc, I'll merge for now but I'd like someone to see if an update for this plugin exists that fixes the warnings on their end

**Comment by minenice55** [comment]
will have to cherry pick into r1 due to combined changes

**Pull request merged**
