### PR TITLE
Flan’s various, large improvements

### PR DESCRIPTION
**Pull request by ThatZeoMan**
**READY TO MERGE!**

Over 1500 files changed? Wow!

From what I understand, these changes include:

- Karate Man adjustments
- Language SFX
- Karate Man flow shenanigans
- fixed the clappy trio bop bug
- Marching orders inputs!!
- Assetbundle support for many games
- Karate man pot breaking sfx
- Sign animation for clappy trio
- Many other adjustments and additions to various games & editor features

### CODE REVIEW

**Comment by blank3times** [comment]
scheez that's large

**Comment by blank3times** [comment]
AmyDesu (/Jellirby??) I saw the custom remixes you made and they look cool =]

**Comment by ThatZeoMan** [comment]
PR is ready for review! Hopefully the merge conflicts aren’t too bad.

**Comment by minenice55** [comment]
I want to merge in the marcher changes to start slow, but they're combined with changes to other minigames I don't want to add yet. Is it possible to get a separate PR with just those changes?

**Comment by Amy54Desu** [comment]
> I want to merge in the marcher changes to start slow, but they're combined with changes to other minigames I don't want to add yet. Is it possible to get a separate PR with just those changes?

Would suck to seperate them

**Comment by minenice55** [comment]
closing as no feature separation has been made.

**Pull request closed without merging**
