### PR TITLE
Sumo Brothers Bug Fixes + More Customizability

### PR DESCRIPTION
**Pull request by RaffyTaffy14**
# `"We... are the Sumo Bros..."` _-The Sumo Bros, 2016_

### Recolorable Background
The default gradient (yes it is a gradient) background can now be recolored with the new `Background Appearance` event

### Force Slaps / Stomps
You can now force a slap/stomp input to play anytime, anywhere!
- Event has a bunch of customizable toggles

"Why would you want to do this?"
I don't know, thought it would be funny.

Misusing this event can and will break stuff, so if something breaks, that's on you for using it stupidly. (unless there is an actual bug when using it not stupidly, then uh oh)

## Tweaks / Bug Fixes
The `Alternate Backgrounds` toggle in the `Finishing Pose` event will now remember the last background even after switching games.

Fixed the game refusing to load/play more than one input when cueing in Slaps/Stomps from another game

### CODE REVIEW

**Comment by RaffyTaffy14** [comment]
also still no asset bundles because screw you, unity screwed me

**Comment by minenice55** [comment]
fix conflicts so that I can merge (in your case just use the file present on origin)

**Comment by RaffyTaffy14** [comment]
huzzah

**Comment by RaffyTaffy14** [comment]
thank you father minenice

**Pull request merged**
